title: Hoy en el espacio
description: Una noticia del espacio por día.
url: "https://lezama.github.io"
baseurl: "/espacio-bot"
timezone: America/Montevideo
permalink: /:year/:month/:day/
defaults:
  - scope:
      type: posts
    values:
      layout: post
exclude:
  - fetch.py
  - prompt.md
  - README.md
  - LICENSE
